apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-specific
spec:
  podSelector:
    matchLabels:
      env: production
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network: different-namespace
      ports:
        - port: 8080
          protocol: TCP
