# This lab creates a local PersistentVolume with a StorageClass name
# and proceeds with defining a PersistentVolumeClaim that requests a
# storage. After storage resources definition, we test it out with a Pod that runs
# nginx with provided volume.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sc
  hostPath:
    path: /mnt/local-pv-data
  capacity: 
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sc
  resources:
    requests:
      storage: 999Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-app
      image: bitnami/nginx
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: nginx-vol
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: local-pvc
