apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/my-local-pv-data
  capacity:
    storage: 1Gi

